### ISSUE TITLE
ASCII character/key mapping?

### ISSUE THREAD

**Issue by jimclark** [jim11662418/wheelwriter-teletype#3]
I'm slowly working towards implementing this project, and just got an ASCII printwheel for my Wheelwriter 3 (first-gen, not Series II or whatever).  Contrary to this comment:

https://github.com/jim11662418/IBM_Wheelwriter_Teletype/blob/121553c73c0d2220dec38d66a26cce450ddf5e69/SDCC/wheelwriter.c#L72-L73

I get the pipe character by pressing Code+½ (or Code+}), as it takes the place of the ² character, similar to how backslash takes the place of ³ and is thus typed by Code+] (as you've commented).

It's going to be a while before I'm able to run the system end-to-end, but I just want to check if that's a typo, or maybe some funny quirk that I'll have to look out for?

**Comment by jim11662418** [comment]
The behavior that you're seeing is correct. The confusion is because of a mistake on my part when writing the comments. I had replaced original the '½' and ']' keys with '[' and ']' keys from a PC keyboard. I've since corrected the comments. Thanks for catching the error.
![IMG_0325](https://github.com/user-attachments/assets/360de3a4-68dc-4a3b-803a-dc7173e2dca9)

**Comment by jim11662418** [comment]
I'm guessing that you'll get notification from github that this issue has
been closed. if not...

The behavior that you're seeing is correct. The confusion is because of a
mistake on my part when writing the comments. I had replaced original the
'½' and ']' keys with '[' and ']' keys from a PC keyboard. I've since
corrected the comments. Thanks for catching the error.

**Comment by jimclark** [comment]
Great, thanks for checking!  (I did get the ping from the first message.)  Although now I've got another question -- does your code 'transpose' the keypresses so that one key does left bracket and curly brace, and the other does right bracket and curly brace (as a modern keyboard does), or is it 'stock' with the left key for braces and the right key for brackets?

**Comment by jim11662418** [comment]
It works like a PC keyboard. Left bracket and left curly brace on one key
and right bracket and right curly brace on the other key.
